---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache package
    apt:
      name: apache2 
    when: ansible_distribution == "Ubuntu"

  - name: add php support for apache
    dnf:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: update repository index
    dnf:
      update_cache: yes
    when: ansible_distribution == "Rocky"

  - name: install apache package
    dnf:
      name: httpd
    when: ansible_distribution == "Rocky"

  - name: add php support for apache
    dnf:
      name: php
      state: latest
    when: ansible_distribution == "Rocky"
