---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    dnf:
      update_only: yes
      state: latest

  - name: install httpd package
    dnf:
      name: httpd.x86_64 
      state: absent
