spool ACCEPT_Directories.log
create or replace directory MIJNPNO_INGELEZEN as '/u03/db_dirs/ota/accept/inkomend/ingelezen';
create or replace directory MIJNPNO_INKOMEND as '/u03/db_dirs/ota/accept/inkomend';
create or replace directory MIJNPNO_PDF as '/u03/db_dirs/ota/accept/pdf';
create or replace directory POSTCODEMUTATIES as '/u03/db_dirs/ota/accept/postcodemutaties';
create or replace directory MIJNPNO_UITGAAND as '/u03/db_dirs/ota/accept/uitgaand';
create or replace directory UWV_SUAG_DIR as '/u03/db_dirs/ota/accept/external_tables/uwv_suag';
create or replace directory EXT_WAO_LOAD_DIR as '/u03/db_dirs/ota/accept/external_tables/wao_tape';
create or replace directory ADP_XML as '/u03/db_dirs/ota/accept/adp_xml';
create or replace directory BRIEF_PENSIONERING as '/u03/db_dirs/ota/accept/pb/3-werkmap_brieven_pensionering';
create or replace directory BRIEF_RIS as '/u03/db_dirs/ota/accept/pb/2-werkmap_brieven_ris';
create or replace directory UITGAANDE_WAARDEOVERDRACHT as '/u03/db_dirs/ota/accept/pb/uitgaande_waardeoverdracht';
create or replace directory BANKBESTANDEN_FOUT as '/u03/db_dirs/ota/accept/pb/bankbestanden/fout';
create or replace directory BANKBESTANDEN_VERWERKT as '/u03/db_dirs/ota/accept/pb/bankbestanden/verwerkt';
create or replace directory BANKBESTANDEN_STAGING as '/u03/db_dirs/ota/accept/pb/bankbestanden/staging';
create or replace directory WO_IN as '/u03/db_dirs/ota/accept/pb/waardeoverdracht_in/wo_in';
create or replace directory EENMALIGE_BRIEVEN as '/u03/db_dirs/ota/accept/pb/brieven/eenmalige_brieven';
create or replace directory FISCALE_TOETS as '/u03/db_dirs/ota/accept/pb/fiscale_toets';
create or replace directory BRIEVEN as '/u03/db_dirs/ota/accept/pb/brieven';
create or replace directory PDF_AO_OVERZICHT as '/u03/db_dirs/ota/accept/pb/ao_overzicht';
create or replace directory MUTATIELIJST_PDF as '/u03/db_dirs/ota/accept/pb/mutatielijst';
create or replace directory JAARWERK_DUMP as '/u03/db_dirs/ota/accept/pb/jaarwerk';
create or replace directory ADP_DUMP as '/u03/db_dirs/ota/accept/pb/adp';
create or replace directory PREMIENOTA_PDF as '/u03/db_dirs/ota/accept/pb/premienota';
create or replace directory INADMIN_UIT as '/u03/db_dirs/ota/accept/pb/inadmin_uit';
create or replace directory INADMIN_IN as '/u03/db_dirs/ota/accept/pb/inadmin_in';
create or replace directory FACTOR_A as '/u03/db_dirs/ota/accept/pb/brieven/factora';
create or replace directory GEWIJZIGDE_UITKERING as '/u03/db_dirs/ota/accept/pb/brieven/gewijzigde_uitkering';
create or replace directory INDIVIDUELE_OFFERTE as '/u03/db_dirs/ota/accept/pb/brieven/individuele_offerte';
create or replace directory INFORMATIEMIDDAG as '/u03/db_dirs/ota/accept/pb/brieven/informatiemiddag';
create or replace directory NEGEN_MAANDS_BRIEVEN as '/u03/db_dirs/ota/accept/pb/brieven/negen_maands_brieven';
create or replace directory WOKP_UIT as '/u03/db_dirs/ota/accept/pb/uitgaande_waardeoverdracht/wokp_uit';
create or replace directory UPO_DIR as '/u03/db_dirs/ota/accept/pb/upo_dir';
create or replace directory WOKP_IN as '/u03/db_dirs/ota/accept/pb/waardeoverdracht_in/wokp_in';
create or replace directory RUIF_FOUT as '/u03/db_dirs/ota/accept/risdata/da/t_en_t/pb/vo107/foutverwerkt';
create or replace directory RUIF_UITGAAND as '/u03/db_dirs/ota/accept/risdata/da/t_en_t/pb/vo105/aangemaakt';
create or replace directory RUIF_VERWERKT as '/u03/db_dirs/ota/accept/risdata/da/t_en_t/pb/vo107/verwerkt';
create or replace directory RUIF_STAGING as '/u03/db_dirs/ota/accept/risdata/da/t_en_t/pb/vo107/staging';
create or replace directory RUIF_INKOMEND as '/u03/db_dirs/ota/accept/risdata/da/t_en_t/pb/vo107/ontvangen';
create or replace directory AOP_PAIN as '/u03/db_dirs/ota/accept/bankbestanden';
create or replace directory BANKBESTANDEN_INKOMEND as '/u03/db_dirs/ota/accept/nav_exchange/ris/kwo';
create or replace directory BANKBESTANDEN_UITGAAND as '/u03/db_dirs/ota/accept/nav_exchange/ris/kwo';
create or replace directory NAVISION_PBDIR as '/u03/db_dirs/ota/accept/nav_exchange/ris';
create or replace directory NAVISION_DIR as '/u03/db_dirs/ota/accept/nav_exchange/ris';
create or replace directory PENSIOEN123 as '/u03/db_dirs/ota/accept/pensioen123';
create or replace directory BRIEVEN_EMAIL as '/u03/db_dirs/ota/accept/pb/brieven_email';
create or replace directory BRIEF_PENSIONERING_EMAIL as '/u03/db_dirs/ota/accept/pb/brieven_pensionering_email';
create or replace directory BRIEF_RIS_EMAIL as '/u03/db_dirs/ota/accept/pb/brief_ris_email';
grant READ,WRITE on directory BRIEVEN_EMAIL to PNODATA;
grant READ,WRITE on directory BRIEF_PENSIONERING_EMAIL to PNODATA;
grant READ,WRITE on directory BRIEF_RIS_EMAIL to PNODATA;
grant READ on directory SYS.RUIF_STAGING to RUIF;
grant EXECUTE on directory SYS.NAVISION_DIR to PNODATA;
grant READ on directory SYS.NAVISION_DIR to PNODATA;
grant READ on directory SYS.FISCALE_TOETS to PNODATA;
grant READ,WRITE on directory SYS.FACTOR_A to PNODATA;
grant READ,WRITE on directory SYS.GEWIJZIGDE_UITKERING to PNODATA;
grant READ,WRITE on directory SYS.INFORMATIEMIDDAG to PNODATA;
grant READ,WRITE on directory SYS.NEGEN_MAANDS_BRIEVEN to PNODATA;
grant READ,WRITE on directory SYS.INDIVIDUELE_OFFERTE to PNODATA;
grant READ,WRITE on directory SYS.WOKP_UIT to PNODATA;
grant READ,WRITE on directory SYS.WOKP_IN to PNODATA;
grant READ on directory SYS.BRIEVEN to PNODATA;
grant READ on directory SYS.PDF_AO_OVERZICHT to PNODATA;
grant READ on directory SYS.MUTATIELIJST_PDF to PNODATA;
grant READ on directory SYS.JAARWERK_DUMP to PNODATA;
grant READ on directory SYS.UWV_SUAG_DIR to PNODATA;
grant READ on directory SYS.RUIF_FOUT to PNODATA;
grant READ on directory SYS.RUIF_UITGAAND to PNODATA;
grant READ on directory SYS.RUIF_VERWERKT to PNODATA;
grant READ on directory SYS.RUIF_STAGING to PNODATA;
grant READ on directory SYS.RUIF_INKOMEND to PNODATA;
grant READ on directory SYS.POSTCODEMUTATIES to PNODATA;
grant READ on directory SYS.PREMIENOTA_PDF to PNODATA;
grant READ on directory SYS.AOP_PAIN to PNODATA;
grant READ on directory SYS.EXT_WAO_LOAD_DIR to PNODATA;
grant READ on directory SYS.MIJNPNO_PDF to PNODATA;
grant READ on directory SYS.MIJNPNO_INGELEZEN to PNODATA;
grant READ on directory SYS.MIJNPNO_UITGAAND to PNODATA;
grant READ on directory SYS.MIJNPNO_INKOMEND to PNODATA;
grant READ on directory SYS.UPO_DIR to PNODATA;
grant READ on directory SYS.UITGAANDE_WAARDEOVERDRACHT to PNODATA;
grant READ on directory SYS.BANKBESTANDEN_FOUT to PNODATA;
grant READ on directory SYS.BANKBESTANDEN_VERWERKT to PNODATA;
grant READ on directory SYS.BANKBESTANDEN_UITGAAND to PNODATA;
grant READ on directory SYS.BANKBESTANDEN_INKOMEND to PNODATA;
grant READ on directory SYS.BANKBESTANDEN_STAGING to PNODATA;
grant READ on directory SYS.WO_IN to PNODATA;
grant READ on directory SYS.ADP_XML to PNODATA;
grant READ on directory SYS.EENMALIGE_BRIEVEN to PNODATA;
grant READ on directory SYS.PENSIOEN123 to PNODATA;
grant READ on directory SYS.BRIEF_PENSIONERING to PNODATA;
grant READ on directory SYS.INADMIN_UIT to PNODATA;
grant READ on directory SYS.INADMIN_IN to PNODATA;
grant READ on directory SYS.BRIEF_RIS to PNODATA;
grant WRITE on directory SYS.NAVISION_DIR to PNODATA;
grant WRITE on directory SYS.FISCALE_TOETS to PNODATA;
grant WRITE on directory SYS.BRIEVEN to PNODATA;
grant WRITE on directory SYS.PDF_AO_OVERZICHT to PNODATA;
grant WRITE on directory SYS.MUTATIELIJST_PDF to PNODATA;
grant WRITE on directory SYS.JAARWERK_DUMP to PNODATA;
grant WRITE on directory SYS.UWV_SUAG_DIR to PNODATA;
grant WRITE on directory SYS.RUIF_FOUT to PNODATA;
grant WRITE on directory SYS.RUIF_UITGAAND to PNODATA;
grant WRITE on directory SYS.RUIF_VERWERKT to PNODATA;
grant WRITE on directory SYS.RUIF_STAGING to PNODATA;
grant WRITE on directory SYS.RUIF_INKOMEND to PNODATA;
grant WRITE on directory SYS.POSTCODEMUTATIES to PNODATA;
grant WRITE on directory SYS.PREMIENOTA_PDF to PNODATA;
grant WRITE on directory SYS.AOP_PAIN to PNODATA;
grant WRITE on directory SYS.EXT_WAO_LOAD_DIR to PNODATA;
grant WRITE on directory SYS.MIJNPNO_PDF to PNODATA;
grant WRITE on directory SYS.MIJNPNO_INGELEZEN to PNODATA;
grant WRITE on directory SYS.MIJNPNO_INKOMEND to PNODATA;
grant WRITE on directory SYS.MIJNPNO_UITGAAND to PNODATA;
grant WRITE on directory SYS.UPO_DIR to PNODATA;
grant WRITE on directory SYS.UITGAANDE_WAARDEOVERDRACHT to PNODATA;
grant WRITE on directory SYS.BANKBESTANDEN_FOUT to PNODATA;
grant WRITE on directory SYS.BANKBESTANDEN_VERWERKT to PNODATA;
grant WRITE on directory SYS.BANKBESTANDEN_STAGING to PNODATA;
grant WRITE on directory SYS.BANKBESTANDEN_INKOMEND to PNODATA;
grant WRITE on directory SYS.BANKBESTANDEN_UITGAAND to PNODATA;
grant WRITE on directory SYS.WO_IN to PNODATA;
grant WRITE on directory SYS.ADP_XML to PNODATA;
grant WRITE on directory SYS.EENMALIGE_BRIEVEN to PNODATA;
grant WRITE on directory SYS.PENSIOEN123 to PNODATA;
grant WRITE on directory SYS.BRIEF_PENSIONERING to PNODATA;
grant WRITE on directory SYS.BRIEF_RIS to PNODATA;
grant WRITE on directory SYS.INADMIN_IN to PNODATA;
grant WRITE on directory SYS.INADMIN_UIT to PNODATA;
grant READ on directory SYS.RUIF_STAGING to ONTW;
grant WRITE on directory SYS.RUIF_STAGING to ONTW;
grant EXECUTE on directory SYS.AOP_PAIN to NEIL with grant option;
grant READ on directory SYS.AOP_PAIN to NEIL with grant option;
grant READ on directory SYS.NAVISION_PBDIR to NEIL with grant option;
grant READ on directory SYS.NAVISION_DIR to NEIL with grant option;
grant READ on directory SYS.ADP_DUMP to NEIL with grant option;
grant WRITE on directory SYS.AOP_PAIN to NEIL with grant option;
grant WRITE on directory SYS.NAVISION_PBDIR to NEIL with grant option;
grant WRITE on directory SYS.NAVISION_DIR to NEIL with grant option;
grant WRITE on directory SYS.ADP_DUMP to NEIL with grant option;
grant EXECUTE on directory SYS.BRIEF_PENSIONERING to JACOB with grant option;
grant EXECUTE on directory SYS.BRIEF_RIS to JACOB with grant option;
grant READ on directory SYS.BRIEF_PENSIONERING to JACOB with grant option;
grant READ on directory SYS.BRIEF_RIS to JACOB with grant option;
grant WRITE on directory SYS.BRIEF_PENSIONERING to JACOB with grant option;
grant WRITE on directory SYS.BRIEF_RIS to JACOB with grant option;
grant READ on directory SYS.BANKBESTANDEN_UITGAAND to PNODATA;
grant WRITE on directory SYS.BANKBESTANDEN_UITGAAND to PNODATA;
grant READ on directory SYS.NAVISION_PBDIR to RIS;
grant READ on directory SYS.NAVISION_DIR to RIS;
grant READ on directory SYS.ADP_DUMP to RIS;
grant WRITE on directory SYS.NAVISION_PBDIR to RIS;
grant WRITE on directory SYS.NAVISION_DIR to RIS;
grant WRITE on directory SYS.ADP_DUMP to RIS;
grant READ on directory SYS.AOP_PAIN to PNODATA;
grant READ on directory SYS.ADP_DUMP to PNODATA;
grant READ on directory SYS.NAVISION_PBDIR to PNODATA;
grant WRITE on directory SYS.AOP_PAIN to PNODATA;
grant WRITE on directory SYS.ADP_DUMP to PNODATA;
grant WRITE on directory SYS.NAVISION_PBDIR to PNODATA;
-- grant READ on directory PNODATA.UITGAANDE_WAARDEOVERDRACHT to SANDRA;
-- grant READ on directory PNODATA.UITGAANDE_WAARDEOVERDRACHT to CHRISW;
-- grant READ on directory PNODATA.UITGAANDE_WAARDEOVERDRACHT to CHANTAL;
-- grant READ on directory PNODATA.UITGAANDE_WAARDEOVERDRACHT to CARLA;
spool off
