DROP PROFILE SYSTEM_ACCOUNT CASCADE;

CREATE PROFILE SYSTEM_ACCOUNT LIMIT
  SESSIONS_PER_USER 10000
  CPU_PER_SESSION DEFAULT
  CPU_PER_CALL DEFAULT
  CONNECT_TIME DEFAULT
  IDLE_TIME DEFAULT
  LOGICAL_READS_PER_SESSION DEFAULT
  LOGICAL_READS_PER_CALL DEFAULT
  COMPOSITE_LIMIT DEFAULT
  PRIVATE_SGA DEFAULT
  FAILED_LOGIN_ATTEMPTS 5
  INACTIVE_ACCOUNT_TIME UNLIMITED
  PASSWORD_LIFE_TIME UNLIMITED
  PASSWORD_REUSE_TIME 365
  PASSWORD_REUSE_MAX 20
  PASSWORD_LOCK_TIME 1
  PASSWORD_GRACE_TIME 5
  PASSWORD_VERIFY_FUNCTION ORA12C_STRONG_VERIFY_FUNCTION;
