spool cre_cmgmon.log

--CREATE profile MONITOR password_life_time UNLIMITED;
DROP USER CMGMON;
CREATE USER CMGMON
IDENTIFIED BY "tnvd%sk-4fkduvNH777jOZJ" 
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
PROFILE MONITOR
ACCOUNT UNLOCK;

DROP ROLE ROLE_CMGMON;
CREATE ROLE ROLE_CMGMON;
GRANT ROLE_CMGMON TO CMGMON;
GRANT CREATE SESSION TO ROLE_CMGMON;

GRANT SELECT ON DBA_TABLESPACES TO ROLE_CMGMON; 
 GRANT SELECT ON DBA_DATA_FILES TO ROLE_CMGMON; 
 GRANT SELECT ON DBA_TEMP_FILES TO ROLE_CMGMON; 
 GRANT SELECT ON DBA_FREE_SPACE TO ROLE_CMGMON; 
 GRANT SELECT ON DBA_ROLE_PRIVS TO ROLE_CMGMON; 
 GRANT SELECT ON V_$SYSSTAT TO ROLE_CMGMON; 
 GRANT SELECT ON V_$SESSION TO ROLE_CMGMON; 
 GRANT SELECT ON V_$SYSTEM_EVENT TO ROLE_CMGMON; 
 GRANT SELECT ON V_$PARAMETER TO ROLE_CMGMON; 
 GRANT SELECT ON V_$DATABASE TO ROLE_CMGMON; 
 GRANT SELECT ON V_$INSTANCE TO ROLE_CMGMON; 
 GRANT SELECT ON V_$LICENSE TO ROLE_CMGMON; 
 GRANT SELECT ON V_$LOG TO ROLE_CMGMON; 
 GRANT SELECT ON V_$TEMPFILE TO ROLE_CMGMON; 
 GRANT SELECT ON V_$DATAFILE TO ROLE_CMGMON; 
 GRANT SELECT ON V_$TEMP_SPACE_HEADER TO ROLE_CMGMON; 
 GRANT SELECT ON V_$SORT_USAGE  TO ROLE_CMGMON; 
 GRANT SELECT ON V_$FILESTAT TO ROLE_CMGMON; 
 CREATE OR REPLACE VIEW X_$KCBWH AS SELECT * FROM X$KCBWH; 
 CREATE OR REPLACE VIEW X_$KCBSW AS SELECT * FROM X$KCBSW; 
 GRANT SELECT ON X_$KCBWH TO ROLE_CMGMON; 
 GRANT SELECT ON X_$KCBSW TO ROLE_CMGMON;

--GRANT ROLE_CMGMON TO rrdora;
GRANT SELECT ON DBA_USERS TO ROLE_CMGMON;
GRANT SELECT ON DBA_OBJECTS TO ROLE_CMGMON;
GRANT SELECT ON V_$OPTION TO ROLE_CMGMON;
GRANT SELECT ON DBA_FEATURE_USAGE_STATISTICS TO ROLE_CMGMON;
GRANT SELECT ON DBA_REGISTRY_HISTORY TO ROLE_CMGMON;

--Database on an ASM instance.
--grant select on v_$asm_diskgroup to ROLE_CMGMON;
--grant select on v_$asm_disk to ROLE_CMGMON;
--grant select on v_$asm_file to ROLE_CMGMON;
--grant select on v_$asm_alias to ROLE_CMGMON;
--grant select on v_$asm_client to ROLE_CMGMON;

spool off
