shut immediate;
startup mount;
alter database noarchivelog;
alter database open;
alter system set memory_max_target=0 scope=spfile;
alter system set memory_target=0  scope=spfile;
alter system set SGA_MAX_SIZE=11264m scope=spfile;
alter system set SGA_TARGET=10305m scope=spfile; 
alter system set PGA_AGGREGATE_TARGET=2048m scope=spfile;
alter system set job_queue_processes=16 scope=both;
shut immediate;
startup;
ALTER SYSTEM set shared_pool_size= 5G scope=both;
ALTER SYSTEM set java_pool_size= 256M scope=both;
ALTER SYSTEM set large_pool_size= 256M scope=both;
ALTER SYSTEM set streams_pool_size= 256M scope=both;
create pfile from spfile;
